export const WORDNIK_API = 'http://api.wordnik.com:80/v4/words.json/randomWord?hasDictionaryDef=true&includePartOfSpeech=noun&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=5&maxLength=11&api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'
export const LETTER_MISSED = 'LETTER_MISSED'
export const LETTER_HIT = 'LETTER_HIT'
export const END_GAME = 'END_GAME'
export const NEW_WORD = 'NEW_WORD'
